<?php
$newsNumber = 30;
      $news = array (
                      array("title" => "Bowling🎳", "texte" => "avec cléa et kyllian on a fait du bowling et c´étais trop bien, et on a marché sous un ponds", "date" => "01 octobre 2022","img"=>"bowling.png"),
                      array("title" => "j'ai eu un nouveau setup🔌", "texte" => "pour noel j'ai finalement pu complété mon setup: rentré(💻Pc), annive(🖥Écran), noel(⌨Clavier 🖱souris 🎧casque)", "date" => "25 decembre 2020","img"=>"Gamerz.png"),
                      array("title" => "Halloween", "texte" => "notre petite bourgade de ferney a encore une fois envahie par les demon de minuits🕺 en ce mois d'Octobre", "date" => "03 Octobre 2022","img"=>"halowin.png"),
                      array("title" => "Mmmmh...😋", "texte" => "Une invasion plutot en ce mois de Mars nous a pousez a faire des Ravioli d'Alien. La viande a un gouts de haribo en un peux plus fesandé.", "date" => "09 Mars 2021","img"=>"ravioli.png"),
                      array("title" => "Jean Démondela retrouvé mort", "texte" => "La réalité fu encore une fois fusioné a une autre a cause d'un missclick de <a href=\"https://www.youtube.com/watch?v=Ee5ekA4Y4Ok\">Docteur MORDRID</a>. jean l'intruder est la seul victime a déclarer", "date" => "36 Mars 2021","img"=>"demon.png"),
                      array("title" => "méditaion🧘‍♂️", "texte" => "J'ai finalement réusis a effectuer un Tchoume Cosmique a traver la réalité", "date" => "02 aout 2022","img"=>"medite.png"),
                      array("title" => "Lego Konigesgg Jesko <a href=\"https://www.lego.com/fr-fr/product/koenigsegg-jesko-76900\">🏎</a>", "texte" => "j'ai construi une magnifique tuture🚗", "date" => "02 novembre 2022","img"=>"jesko.jpg"),
                      array("title" => "j'en avais une enorme envie😢", "texte" => "après 10 ans de recherche le cadavre de grosquick a finalement été retrouver, le principale suspect quicky nis toute implication", "date" => "02 aout 2012","img"=>"grosquik.jpg"),
                      array("title" => "Justice a été rendu🙄", "texte" => "après 10 ans de suposition d'enquete puis de procès. quicky enfin areté pour c'est méfais.", "date" => "02 aout 2022","img"=>"nesquik.png"),
                      array("title" => "🏳‍🌈Le Mariage de GROS Gay👨‍❤️‍💋‍👨", "texte" => "le mariage pour tous a finalement été légalisé.. et c'est une bonne nouvelle ! je croie🤔", "date" => "17 mai 2013","img"=>"gay.png"),
                      array("title" => "🦾Mon clone a maitriser l'armonie omnipotante !🤯", "texte" => "mon clone a maitriser un pouvoir luis permentant de demander a 🌌l'univer tout Ses désire", "date" => "11 septembre 2006","img"=>"HEYE.png"),
                      array("title" => "Macron a été réelue🛡", "texte" => "🎇macron🎇 a été réelu pour la cinquième fois depuis l'insuréection de 2033🔪, sont manda promet l'anilation définitive des pauvre.", "date" => "12 Chiranbre 2053","img"=>"macron.png"),
                      array("title" => "Caroline d'enjoue vole🎈", "texte" => "After les explosion💥 pendant la guerre du Gaz. il est commun de naitre mutant. caroline a voler des sucette🍭 elle sera donc executer🪓", "date" => "11 aout 2027","img"=>"legs.png"),
                      array("title" => "Gens avoir lit ont 20% de mourire😮", "texte" => "d'après de récantes études📚 il a été prouvé que les lit n'étais pas source d'imortalité, Mais des achteur de EMMA on manger des fraise", "date" => "16 janvier 2019","img"=>"lit.png"),
                      array("title" => "🍑les citrouille c'est SO 2009👱‍♀️", "texte" => "Nabila a di les citrouil son démoder et que cet ané nou aurion use des banana🍌 or papaya🥭, et son cul sera gros que le Monts Réal.", "date" => "07 fevrier 2009","img"=>"haha.png"),
                      array("title" => "😳Putin a lebron james un ours🐻", "texte" => "michka finalement avouez c'est sentiment a putin, et putin a baiser michka... voila voila", "date" => "03 juillet 2011","img"=>"putin.png"),
                      array("title" => "la friperie de bobby joe", "texte" => "a fermé pour cause d'insalubrité, et 15 demi douzaine de cadavre fue découver dans le garde mangé, de quoi tenir tout l'hiver", "date" => "1796","img"=>"imonde.png"),
                      array("title" => "le DISEL vous 50% moins inteligens", "texte" => "d'après une étude mener par le scientifique kevin gazoil prouverait l'essance augmente votre IQ de 6 poivron🍆 et better votre Chant de vision🤯", "date" => "11 janvier 2001","img"=>"Megamind.png"),
                      array("title" => "J'ai upgread mon setup🔌🔌", "texte" => "après noel des traveau et un achat de souris logitech. mon setup est meilleur que jamais.", "date" => "29 décembre 2022","img"=>"Gamerz2.png"),
                      array("title" => "Nous avons vaincu negro!!🤗", "texte" => "Notre carrière dans la street a evolution victoir avec 13 combot et 15415 point de diferrence", "date" => "entre décembres et octobre 2022","img"=>"Drift Clash.jpg"),
                      array("title" => "les deprésif💅", "texte" => "les personne depréssif on dévlopper des superpouvoir... jsp pourquoi", "date" => "octobre 2057","img"=>"raven.png"),
                      array("title" => "jean lassal virée de l'AN", "texte" => "après des message contre versé sur une messagerie, le celebre nettoyeur de vitre a été banni", "date" => "mais 2023","img"=>"meme2.png"),
                      array("title" => "STATCHE oc (nepasvolésilvousplait)", "texte" => "il est le Youtuber le plus suivi, comptabilisant plus de 17,6 millions d'abonné. Il possède également la chaîne Cyprien Gaming avec cyprien", "date" => "entre décembres et octobre 2022","img"=>"STYLE.png"),
                      array("title" => "LAPIZZA🍕", "texte" => "oggi apriremo neonati con pokemon figli di puttana", "date" => "la makina 2022","img"=>"lapizza.png"),
                      array("title" => "voiture", "texte" => "voiture tu voiture voit re voiture turevoi tutu voire tutre voivovivovu vutori", "date" => "voiture 2022","img"=>"koniseg.png"),
                      array("title" => "Meurte chez Apperture🤣", "texte" => "la nouvel branche d'Apperture science travail sur des Macron en 9mm Stinger. Et donc des test balistic sur Humain parfaitment fonctionnel", "date" => "decembre 1992","img"=>"startup.jpg"),
                      array("title" => "Tom est mort👻", "texte" => "Tom c'est fait 1V3 tah gars du nord tu connais. et c'est agresseur on décider de l'EMOTE c'est enculer", "date" => "31 decembre 2022","img"=>"tom.png"),
                      
                      
                );